name: Retrain and Deploy Model

on:
  schedule:
    - cron: '0 4 * * *'  # Runs every day at 4 AM UTC
  workflow_dispatch:  # Optional: lets you trigger manually

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ontrend-db

      - name: Trigger Cloud Build to retrain and deploy
        run: |
          gcloud builds submit --config cloudbuild.yaml --region=asia-southeast1

        